(function(){
var s = "<"+"div class=\"adiply_ad_holder\" style=\"width:160px;height:600px;margin:0;padding:0\">\n";
s += "<"+"/div>\n";
s += "<"+"script type=\"text/javascript\">\n";
s += "var adiply_divs = document.getElementsByClassName(\"adiply_ad_holder\");\n";
s += "var adiply_final_div_id = \"adiply_ad_holder_\" + Math.floor((Math.random() * 100000) + 1);\n";
s += "for(var i=0;i<"+"adiply_divs.length; i++){\n";
s += "     if(adiply_divs[i].id) continue;\n";
s += "     adiply_divs[i].setAttribute(\"id\", adiply_final_div_id);\n";
s += "     break;\n";
s += "}\n";
s += "\n";
s += "  var OX_ads = OX_ads || [];\n";
s += "  OX_ads.push({\n";
s += "     slot_id: adiply_final_div_id,\n";
s += "     auid: \"537209676\"\n";
s += "  });\n";
s += "<"+"/script>\n";
s += "<"+"script type=\"text/javascript\" src=\"http://us-ads.openx.net/w/1.0/jstag\"><"+"/script>\n";
s += "<"+"div id=\'beacon_da39aecf90\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'>\n";
s += "<"+"img width=\"0\" height=\"0\" src=\"http://cat.ny.us.criteo.com/delivery/lg.php?cppv=1&cpp=ebX2%2B3xGZTRsMytmR2hKWTRlelJqUnVIcW14ajllWEpQdWl0SmxwTDJNVUJCTnZhQmlXOFFDSEdDaWhjTVR5U3lIeFF5L3psMFgySzRKL0RDdlBxTXhkelFBQUl1TjA1TldQUnJRNVA2WmZ0ZysvU0VBUDg3UGcwN2dveVBacXNsTVIwbVJKcmFJZVZ2ZUE4MXhDbURiQ0xNSVNhMW5KTUN0cmtCN0I1OURGdHUvZC8xQzI3QmMyY2hVSDM0bFBYdGlXQkROcmtNV3JPWGFKSVU1M0pEVDVGdldlQkk3UE9ESDNHVm1kVXlVVjBGMFZrPXw%3D\"/>\n";
s += "<"+"/div>\n";
s += "\n";
document.write(s);})();
